<?php

/**
* @file
* Module Node Expiration Date
* This module allows the addition of an expiration date to nodes. Created by Paola Garcia. 
*/

/**
* Implements hook_help().
*/
function node_expiration_date_help($path, $arg) {
  switch ($path) {
    //General help for the Node Expiration Date module
    case 'admin/help#node_expiration_date':
      return '<p>' . t('This module permits addition of an expiration date to any content in the site. The administrator can configure which content types could have an expiration date.') . '</p>';
  }	
}

/**
* Implements hook_menu().
*/
function node_expiration_date_menu() {
  $items['admin/config/workflow/node_expiration_date'] = array(
    'title' => 'Node Expiration Date settings',
    'description' => 'Settings for module Node Expiration Date',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('node_expiration_date_admin_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'node_expiration_date.admin.inc'
  );
  return $items;
}
